FROM flink:1.19-java11

USER root

# Install Python 3 and pip
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install PyFlink and other Python dependencies
RUN pip3 install --no-cache-dir \
    apache-flink==1.19.0 \
    kafka-python

USER flink

WORKDIR /opt/flink
